
opc = True                              #le asignamos el valor booleano TRUE a una variable que creamos

while opc:                              #mientras que opc sea true se ejecuta...
    try:                                #intenta hacer esto...
        x = int(input("Introduce un elemento para sumar: "))        #ingresando el primer valor
        y = int(input("Introduce otro elemento para sumar: "))      #ingresando el segundo valor

    except ValueError:                                              #si lo anterior genera un error enronces...
        print("\n\t\t\tERROR! Introduce un numero entero :)")
    else:                                                           #si no genera error entonces...
        resultado = x+y                                             #asigna la operacion a una variable
        print ("\n\n\tEl resultado es: ", resultado)                #imprime la variable anterior
    finally:                        #finalmente has esto...
        opc2 = int (input("Presiona 1 para seguir o 2 para salir:  "))      #el usuario ingresa otro valor 
        if opc2==2:                                                         #si el valor es 2 se ejecuta...
            opc = False                                                     #la variable opc se vuelve false y ya no se ejecutara el while
        else:                       #si presiona cualquier otra cosa...
            print ("\n\tSIGAMOS...\n")      #imprimimos mensaje
